### ISSUE TITLE
NOAA station download crash

### ISSUE THREAD

**Issue by initze** [initze/noaaplotter_streamlit#5]
download often fails
![grafik](https://user-images.githubusercontent.com/4864803/227877519-f818ed1f-0cb2-47d5-8386-7ce6e0f630e9.png)

```
File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/noaaplotter_streamlit/streamlit_app.py", line 53, in <module>
    download_from_noaa(data_file, download_start, download_end, ['TMIN', 'TMAX', 'PRCP', 'SNOW'], station_name,
File "/home/appuser/venv/lib/python3.9/site-packages/noaaplotter/download_utils.py", line 33, in download_from_noaa
    datasets_list = Parallel(n_jobs=4)(
File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
File "/home/appuser/venv/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
```

**Comment by initze** [comment]
![grafik](https://github.com/initze/noaaplotter_streamlit/assets/4864803/2492af78-4047-42c2-8051-daaad0cb99df)


```
Downloading data through NOAA API

100%|██████████| 63/63 [00:05<00:00, 11.04it/s][2023-07-22 15:48:59.445172] 

2023-07-22 15:49:28.647 Uncaught app exception

joblib.externals.loky.process_executor._RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker

    r = call_item()

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__

    return self.fn(*self.args, **self.kwargs)

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 588, in __call__

    return [func(*args, **kwargs)

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 588, in <listcomp>

    return [func(*args, **kwargs)

  File "/home/appuser/venv/lib/python3.9/site-packages/noaaplotter/utils.py", line 92, in dl_noaa_api

    d = json.loads(r.text)

  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script

    exec(code, module.__dict__)

  File "/app/noaaplotter_streamlit/streamlit_app.py", line 53, in <module>

    download_from_noaa(data_file, download_start, download_end, ['TMIN', 'TMAX', 'PRCP', 'SNOW'], station_name,

  File "/home/appuser/venv/lib/python3.9/site-packages/noaaplotter/download_utils.py", line 33, in download_from_noaa

    datasets_list = Parallel(n_jobs=4)(

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1944, in __call__

    return output if self.return_generator else list(output)

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1587, in _get_outputs

    yield from self._retrieve()

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1691, in _retrieve

    self._raise_error_fast()

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1726, in _raise_error_fast

    error_job.get_result(self.timeout)

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 735, in get_result

    return self._return_or_raise()

  File "/home/appuser/venv/lib/python3.9/site-packages/joblib/parallel.py", line 753, in _return_or_raise

    raise self._result

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
